# Generated by Django 4.0.6 on 2022-08-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.hostel'),
        ),
    ]
