# Generated by Django 4.0.6 on 2022-08-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0002_alter_user_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='complaints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.complain'),
        ),
    ]
