# Generated by Django 4.0.6 on 2022-08-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0003_alter_user_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='complaints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.complain'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.hostel'),
        ),
    ]
