# Generated by Django 4.0.6 on 2022-08-09 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0007_alter_hostel_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complaints',
        ),
        migrations.AddField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='is_attended',
            field=models.CharField(choices=[('YES', 'YES'), ('ON PROCESS', 'ON PROCESS'), ('NO', 'NO')], default='NO', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='room_no',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '3'), ('5', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26')], max_length=100),
        ),
    ]
