# Generated by Django 4.0.6 on 2022-08-09 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0009_alter_complain_complain_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
